name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: systemd-language-server
            asset_name: systemd-language-server-linux-amd64
        #  not working
        #   - os: ubuntu-latest
        #     target: aarch64-unknown-linux-gnu
        #     binary_name: systemd-language-server
        #     asset_name: systemd-language-server-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: systemd-language-server
            asset_name: systemd-language-server-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: systemd-language-server
            asset_name: systemd-language-server-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: systemd-language-server.exe
            asset_name: systemd-language-server-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Prepare binary
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} release/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} release/${{ matrix.asset_name }}
            chmod +x release/${{ matrix.asset_name }}
          fi
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/${{ matrix.asset_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false 